server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:car-collection;NON_KEYWORDS=user,year
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console